title: "Component proposal: [Component name]"
labels: ["Status: Discussion started", "Type: New component"]
body:
  - type: markdown
    attributes:
      value: |
        # About this component
  - type: textarea
    id: name
    attributes:
      label: Component name
      description: |
        Share the common name(s) for this component.
      value:
      render: bash
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Component description
      description: "Describe the component in a sentence or two."
      value:
      render: bash
    validations:
      required: true
  - type: textarea
    id: need
    attributes:
      label: Design system need
      description: "Explain the need for this component."
      value:
      render: bash
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: Additional information
      description:
      value:
      render: bash
    validations:
      required: false