title: "Component proposal: [Component name]"
labels: ["Status: Discussion started", "Type: New component"]
body:
  - type: markdown
    attributes:
      value: |
        ## Component name
  - type: textarea
    id: name
    attributes:
      label: Share the common name for this component. Include any alternative component names.
      description:
      value:
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Component description
  - type: textarea
    id: description
    attributes:
      label: Component description
      description: "Describe the component in a sentence or two."
      value:
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Design system need
  - type: textarea
    id: need
    attributes:
      label: Explain the need for this component
      description:
      value:
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Additional information
  - type: textarea
    id: need
    attributes:
      label: Share any other information
      description:
      value:
      render: bash
    validations:
      required: false
