title: "Component proposal: [Component name]"
labels: ["Status: Discussion started", "Type: New component"]
body:
  - type: markdown
    attributes:
      value: |
        # About this component
        Share information about the component you'd like to include in USWDS.
  - type: textarea
    id: name
    attributes:
      label: Component name
      description: |
        Share the common name(s) for this component.
      value: |
        ## Component name
        Share the common name(s) for this component.
      render: bash
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Component description
      description: "Provide a short description of the component."
      value:
      render: bash
    validations:
      required: true
  - type: textarea
    id: need
    attributes:
      label: Design system need
      description: "Explain the need for this component."
      value:
      render: bash
    validations:
      required: true
  - type: textarea
    id: design
    attributes:
      label: Component design
      description:
      value:
      render: bash
    validations:
      required: false
  - type: textarea
    id: implementation
    attributes:
      label: Implementation examples
      description:
      value:
      render: bash
    validations:
      required: false
  - type: textarea
    id: usage
    attributes:
      label: Usage
      description:
      value: |
        ## When to use the component
        Define the appropriate use cases for this component.
        ## When to consider something else
        Identify the scenarios where this component would not be the appropriate choice.
      render: bash
    validations:
      required: false
  - type: textarea
    id: usability
    attributes:
      label: Usability considerations
      description:
      value: |
        Identify any key usability considerations. When possible, provide supporting links to research findings or supporting evidence (your own or other research).
      render: bash
    validations:
      required: false
  - type: textarea
    id: accessibility
    attributes:
      label: Accessibility considerations
      description:
      value: |
        Identify any key accessibility considerations. When possible, provide supporting links to research findings or supporting evidence (your own or other research).
      render: bash
    validations:
      required: false