title: "Component proposal: [Component name]"
labels: ["Status: Discussion started", "Type: New component"]
body:
  - type: markdown
    attributes:
      value: |
        # About this component
        Share information about the component you'd like to include in USWDS.
        The goal of this discussion is to build out the information needed to complete the [proposal template](http://www.github.com).
  - type: textarea
    id: name
    attributes:
      label: Component name
      description: "Share the common name(s) for this component."
      value:
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 'Component description'
      description: Describe the component in one sentence.
      value:
    validations:
      required: true
  - type: textarea
    id: need
    attributes:
      label: 'Design system need'
      description: |
        Explain the need for this component.
          - What key interaction or user pattern does this component support? 
          - What gap does this component fill in the Design System? How is this different from existing USWDS components?
          - What problem does this component solve?
          - Does this component directly support any  federal laws, guidance,  or policies?
      value:
    validations:
      required: true
  - type: textarea
    id: design
    attributes:
      label: 'Component design'
      description: Give a detailed description of the functionality of the component.
      value:
    validations:
      required: false
  - type: textarea
    id: implementation
    attributes:
      label: 'Implementation examples'
      description: Provide a list of links to examples of this kind of component on government (preferred) or non-government sites.
      value:
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # Usage
  - type: textarea
    id: usage
    attributes:
      label: Component usage
      description: |
        Define the appropriate use cases for this component.
          - What common interactions does this component support?
          - What does this component need to do to be successful and effective?
          - What kind of content would be ideal for this component?
        Identify the scenarios where this component would not be the appropriate choice.
          - What are common misuses of this type of component?
          - Are there similar interactions that would be better supported by other components?
          - What kind of content should not be added to this component?
      value:
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # Usability and accessibility
  - type: textarea
    id: usability
    attributes:
      label: Usability considerations
      description: |
        Identify any key usability considerations.
          - What does this component need to do to be successful and effective?
          - What are the characteristics of a successful interaction with this component?
          - What would make this component less usable?
          - What are common pitfalls or implementation mistakes associated with this component?
      value:
    validations:
      required: false
  - type: textarea
    id: accessibility
    attributes:
      label: Accessibility considerations
      description: |
        Identify any key accessibility considerations.
          - Will users of any assistive technologies struggle with this component? List any potential risks for users of keyboard navigation, screen readers, zoom magnification, voice command, etc.
          - Are there any audiences that might struggle with this component? 
          - Describe how this component might become inaccessible.
      value:
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # Stakeholders
  - type: textarea
    id: stakeholders
    attributes:
      label: Volunteers and endorsements
      description: |
        Volunteers: Tag any volunteers who are willing to help design, develop, or test this component. 
        Endorsements: If there is significant support from a given agency or group, include their names here and tag any stakeholders.
      value:
    validations:
      required: false
