title: "Component proposal: [Component name]"
labels: ["Status: Discussion started", "Type: New component"]
body:
  - type: markdown
    attributes:
      value: |
        # 1. About this component
        Share information about the component you'd like to include in USWDS.
        The goal of this discussion is to build out the information needed to complete the [proposal template](http://www.github.com).
  - type: input
    id: name
    attributes:
      label: '1.1 Component name'
      description: |
        Share the common name(s) for this component.
      value:
      render: bash
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: '1.2 Component description'
      description: "Provide a short description of the component."
      value:
      render: bash
    validations:
      required: true
  - type: textarea
    id: need
    attributes:
      label: '1.3 Design system need'
      description: "Explain the need for this component."
      value:
      render: bash
    validations:
      required: true
  - type: textarea
    id: design
    attributes:
      label: '1.4 Component design'
      description: Give a detailed description of the functionality of the component.
      value:
      render: bash
    validations:
      required: false
  - type: textarea
    id: implementation
    attributes:
      label: '1.5 Implementation examples'
      description:
      value:
      render: bash
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # 2. Usage
  - type: textarea
    id: usage
    attributes:
      label: Component usage
      description: Define the appropriate use cases for this component and identify the scenarios where this component would not be the appropriate choice.
      value:
      render: bash
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # 3. Usability and accessibility
  - type: textarea
    id: usability
    attributes:
      label: Usability considerations
      description: |
        Identify any key usability considerations.
        When possible, provide supporting links to research findings or supporting evidence (your own or other research).
      value:
      render: bash
    validations:
      required: false
  - type: textarea
    id: accessibility
    attributes:
      label: Accessibility considerations
      description: |
        Identify any key accessibility considerations.
        When possible, provide supporting links to research findings or supporting evidence (your own or other research).
      value:
      render: bash
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # 4. Stakeholders
  - type: textarea
    id: stakeholders
    attributes:
      label: Volunteers, contributors, and endorsements
      description:
      value: |
        Identify any key usability considerations. When possible, provide supporting links to research findings or supporting evidence (your own or other research).
      render: bash
    validations:
      required: false
